Wave9/require name surname
software-mansion-labs/expensify-app-fork pull request #69
Opened 2024-02-22 12:01 UTC by MaciejSWM

WIP

2024-02-27 15:51 UTC, blazejkustra requested changes

2024-02-27 15:51 UTC, blazejkustra commented on src/components/HeaderWithBackButton/index.tsx
> +                progressBarPercentage !== undefined && styles.pl2,
Would this work?
```suggestion
                progressBarPercentage && styles.pl2,
```

2024-02-27 15:51 UTC, blazejkustra commented on src/libs/ValidationUtils.ts
> +function doesContainReservedWord(value: string, reservedWords: readonly string[]): boolean {
Is this change necessary?

2024-02-27 15:51 UTC, blazejkustra commented on src/styles/variables.ts
> +    fontSizeSignInHeroSmallLineHeight: 30.8,
`30.8` is this a correct value?

2024-02-27 15:51 UTC, blazejkustra commented on src/pages/OnboardingPersonalDetails.tsx
> +    const currentUserDetails = currentUserPersonalDetails || {};
How about optional chaining inside component instead of this line?
 ```suggestion
```

2024-02-28 14:14 UTC, MaciejSWM commented on src/components/HeaderWithBackButton/index.tsx
> +                progressBarPercentage !== undefined && styles.pl2,
haha, I think `progressBarPercentage = 0` will be interpreted as false but let me test

2024-02-28 14:16 UTC, MaciejSWM commented on src/styles/variables.ts
> +    fontSizeSignInHeroSmallLineHeight: 30.8,
Yes, precisely as stated in figma. `30.8` is 110% of `fontSizeSignInHeroSmall: 28`. Maybe I should do something like this?
```
fontSize: variables. fontSizeSignInHeroSmall,
lineHeight: variables. fontSizeSignInHeroSmall * 1.1
```
but not sure if this is better

2024-02-28 14:20 UTC, MaciejSWM commented on src/libs/ValidationUtils.ts
> +function doesContainReservedWord(value: string, reservedWords: readonly string[]): boolean {
Unfortunately yes. If removed, typecheck says:
```
rc/pages/OnboardingPersonalDetails.tsx:50:71 - error TS2345: Argument of type 'readonly ["Expensify", "Concierge"]' is not assignable to parameter of type 'string[]'.
  The type 'readonly ["Expensify", "Concierge"]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

50         if (ValidationUtils.doesContainReservedWord(values.firstName, CONST.DISPLAY_NAME.RESERVED_NAMES)) {
                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/pages/OnboardingPersonalDetails.tsx:61:70 - error TS2345: Argument of type 'readonly ["Expensify", "Concierge"]' is not assignable to parameter of type 'string[]'.
  The type 'readonly ["Expensify", "Concierge"]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

61         if (ValidationUtils.doesContainReservedWord(values.lastName, CONST.DISPLAY_NAME.RESERVED_NAMES)) {
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/pages/OnboardingPersonalDetails.tsx:50
```

2024-02-28 14:21 UTC, blazejkustra commented on src/libs/ValidationUtils.ts
> +function doesContainReservedWord(value: string, reservedWords: readonly string[]): boolean {
use `CONST.DISPLAY_NAME.RESERVED_NAMES as string[]`

2024-02-28 14:25 UTC, MaciejSWM commented on src/pages/OnboardingPersonalDetails.tsx
> +    const currentUserDetails = currentUserPersonalDetails || {};
Yeah, wasn't needed. Dropping

2024-02-28 14:49 UTC, MaciejSWM commented on src/libs/ValidationUtils.ts
> +function doesContainReservedWord(value: string, reservedWords: readonly string[]): boolean {
I'm getting
```
Conversion of type 'readonly ["Expensify", "Concierge"]' to type 'string[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  The type 'readonly ["Expensify", "Concierge"]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.ts(2352)
```
🤷‍♂️

2024-02-28 14:52 UTC, MaciejSWM commented on src/components/HeaderWithBackButton/index.tsx
> +                progressBarPercentage !== undefined && styles.pl2,
Yup. That's the case. I only added a comment explaining this scenario

2024-02-28 14:56 UTC, MaciejSWM commented on src/styles/variables.ts
> +    fontSizeSignInHeroSmallLineHeight: 30.8,
This also works:
```
        textHeroSmall: {
            ...headlineFont,
            fontSize: variables.fontSizeSignInHeroSmall,
            lineHeight: '110%',
        },
```
looks like the best option. Going for it

2024-02-28 15:00 UTC, blazejkustra commented on src/libs/ValidationUtils.ts
> +function doesContainReservedWord(value: string, reservedWords: readonly string[]): boolean {
Then your initial code was better 😎

2024-02-28 15:02 UTC, merged